const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const DATA='../data/news.json',CAT='../data/brand_catalog.json',ANALYTICS='../data/analytics.json';
function fmt(iso){if(!iso)return'—';const d=new Date(iso);return Number.isNaN(d.getTime())?'—':d.toLocaleString('vi-VN',{dateStyle:'short',timeStyle:'short'})}
function active(x){return x&&x.status!=='expired'&&(!x.expires_at||Date.parse(x.expires_at)>Date.now())&&(x.code||x.promotion_url)}
async function load(){let news=[],catalog={},analytics={};try{const [a,b,c]=await Promise.all([fetch(DATA,{cache:'no-store'}),fetch(CAT,{cache:'no-store'}),fetch(ANALYTICS,{cache:'no-store'})]);if(a.ok)news=await a.json();if(b.ok)catalog=await b.json();if(c.ok)analytics=await c.json()}catch(e){}
const items=Array.isArray(news)?news.filter(active):[];const cats=catalog.categories||{};const brands=Object.values(cats).flat();
$('#stat-active').textContent=items.length;$('#stat-codes').textContent=items.filter(x=>x.code).length;$('#stat-brands').textContent=brands.length;$('#stat-categories').textContent=Object.keys(cats).length;
$('#health-data').textContent=Array.isArray(news)?'OK':'Unavailable';$('#health-catalog').textContent=Object.keys(cats).length?'OK':'Unavailable';
const latest=items.reduce((a,b)=>Date.parse(a?.last_checked||a?.detected_at||0)>Date.parse(b?.last_checked||b?.detected_at||0)?a:b,items[0]);$('#health-updated').textContent=fmt(latest?.last_checked||latest?.detected_at);if($('#last-sync'))$('#last-sync').textContent=`Kiểm tra ${new Date().toLocaleTimeString('vi-VN')}`;
const badge=$('#health-badge');if(Array.isArray(news)&&Object.keys(cats).length){badge.textContent='Healthy';badge.className='badge ok'}else{badge.textContent='Check';badge.className='badge bad'}
const rows=items.slice().sort((a,b)=>Date.parse(b.last_checked||b.detected_at||0)-Date.parse(a.last_checked||a.detected_at||0)).slice(0,12);$('#offers-table').innerHTML=rows.length?rows.map(x=>`<tr><td><b>${esc(x.merchant||'—')}</b></td><td><span class="type">${x.code?'PROMO CODE':'DEAL'}</span></td><td>${esc(x.discount||x.title||'Official offer')}</td><td>${esc(x.category||'Deals')}</td><td>${esc(fmt(x.last_checked||x.detected_at))}</td></tr>`).join(''):'<tr><td colspan="5">Không có active offer.</td></tr>';
$('#brand-summary').innerHTML=Object.entries(cats).map(([cat,list])=>`<article><strong>${list.length}</strong><span>${esc(cat)}</span></article>`).join('')||'<article><span>Không đọc được catalog.</span></article>';
const configured=analytics&&analytics.configured===true;$('#ga4-status').textContent=configured?'Đã kết nối':'Chưa có dữ liệu';$('#ga4-updated').textContent=fmt(analytics.updated_at);const t=analytics.totals||{};$('#ga4-users').textContent=configured?(t.active_users??0):'—';$('#ga4-sessions').textContent=configured?(t.sessions??0):'—';$('#ga4-pageviews').textContent=configured?(t.pageviews??0):'—';$('#ga4-engagement').textContent=configured?`${t.engagement_rate??0}%`:'—';
const daily=Array.isArray(analytics.daily)?analytics.daily.slice(-10).reverse():[];$('#ga4-daily').innerHTML=daily.length?daily.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.active_users)}</td><td>${esc(x.sessions)}</td><td>${esc(x.pageviews)}</td></tr>`).join(''):'<tr><td colspan="4">Chưa có snapshot GA4. Workflow sẽ tự cập nhật sau khi quyền GA4 hoạt động.</td></tr>';
const pages=Array.isArray(analytics.top_pages)?analytics.top_pages.slice(0,8):[];$('#ga4-pages').innerHTML=pages.length?pages.map(x=>`<tr><td>${esc(x.title||'—')}</td><td>${esc(x.path||'—')}</td><td>${esc(x.pageviews||0)}</td><td>${esc(x.active_users||0)}</td></tr>`).join(''):'<tr><td colspan="4">Chưa có dữ liệu trang.</td></tr>';}
$('#year').textContent=new Date().getFullYear();load();setInterval(load,300000);document.querySelectorAll('.nav').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
