const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const DATA='../data/news.json',CAT='../data/brand_catalog.json';
function fmt(iso){if(!iso)return'—';const d=new Date(iso);return Number.isNaN(d.getTime())?'—':d.toLocaleString('vi-VN',{dateStyle:'short',timeStyle:'short'})}
function active(x){return x&&x.status!=='expired'&&(!x.expires_at||Date.parse(x.expires_at)>Date.now())&&(x.code||x.promotion_url)}
async function load(){let news=[],catalog={};try{const [a,b]=await Promise.all([fetch(DATA,{cache:'no-store'}),fetch(CAT,{cache:'no-store'})]);if(a.ok)news=await a.json();if(b.ok)catalog=await b.json()}catch(e){}
const items=Array.isArray(news)?news.filter(active):[];const cats=catalog.categories||{};const brands=Object.values(cats).flat();
$('#stat-active').textContent=items.length;$('#stat-codes').textContent=items.filter(x=>x.code).length;$('#stat-brands').textContent=brands.length;$('#stat-categories').textContent=Object.keys(cats).length;
$('#health-data').textContent=Array.isArray(news)?'OK':'Unavailable';$('#health-catalog').textContent=Object.keys(cats).length?'OK':'Unavailable';
const latest=items.reduce((a,b)=>Date.parse(a?.last_checked||a?.detected_at||0)>Date.parse(b?.last_checked||b?.detected_at||0)?a:b,items[0]);$('#health-updated').textContent=fmt(latest?.last_checked||latest?.detected_at);$('#last-sync').textContent=`Kiểm tra ${new Date().toLocaleTimeString('vi-VN')}`;
const badge=$('#health-badge');if(Array.isArray(news)&&Object.keys(cats).length){badge.textContent='Healthy';badge.className='badge ok'}else{badge.textContent='Check';badge.className='badge bad'}
const rows=items.slice().sort((a,b)=>Date.parse(b.last_checked||b.detected_at||0)-Date.parse(a.last_checked||a.detected_at||0)).slice(0,12);$('#offers-table').innerHTML=rows.length?rows.map(x=>`<tr><td><b>${esc(x.merchant||'—')}</b></td><td><span class="type">${x.code?'PROMO CODE':'DEAL'}</span></td><td>${esc(x.discount||x.title||'Official offer')}</td><td>${esc(x.category||'Deals')}</td><td>${esc(fmt(x.last_checked||x.detected_at))}</td></tr>`).join(''):'<tr><td colspan="5">Không có active offer.</td></tr>';
$('#brand-summary').innerHTML=Object.entries(cats).map(([cat,list])=>`<article><strong>${list.length}</strong><span>${esc(cat)}</span></article>`).join('')||'<article><span>Không đọc được catalog.</span></article>';}
$('#year').textContent=new Date().getFullYear();load();setInterval(load,300000);document.querySelectorAll('.nav').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
